# SCCSID = @(#)makefile	13.7 92/04/22
#**************************************************************************
#
# Makefile for the MCISTRNG sample program.
#
#**************************************************************************

CC	    = Icc
LINK	    = link386

BASELIBS    = DDE4MBS.LIB OS2386.LIB MMPM2.LIB


CTARG	   = /G3s
COMPILE    = /C+ /W3 /Ki- /Kb- /Ss+ /Gd- /DINCL_32 /Ms
DEBUG	   = /Ti+ /O-

CFLAGS	= $(COMPILE) $(CTARG)

LFLAGS	= /map /nod /noe

all: mcistrng.exe MCISTR1.hlp MCISTR2.hlp MCISTR3.hlp

mcistrng.exe : mcistrng.obj mcistrng.res mcistrng.def
  $(LINK) mcistrng.obj, mcistrng.exe, $(LFLAGS) /ST:36000, $(BASELIBS), \
          mcistrng.def
  rc mcistrng.res

mcistrng.obj : mcistrng.c mcistrng.h
  $(CC) $(CFLAGS) mcistrng.c

mcistrng.res : mcistrng.rc mcistrng.dlg mcistrng.h mcistrng.ico
  rc -r mcistrng.rc

mcistr1.hlp: $*.ipf
  ipfc $*.ipf

mcistr2.hlp: $*.ipf
  ipfc $*.ipf

mcistr3.hlp: $*.ipf
  ipfc $*.ipf
