/*static char *SCCSID = "@(#)checkmem.h 13.1 91/09/04";*/
/****************************************************************************/
/*                                                                          */
/*                    Copyright (c) IBM Corporation 1991                    */
/*                           All Rights Reserved                            */
/*                                                                          */
/* This file contains the definitions and types for the common directory    */
/*                                                                          */
/* Change History:                                                          */
/* Ptm     Date     Pgmr Comments                                           */
/* ======= ======== ===  ================================================== */
/*         05/28/91 MJP  File Created.                                      */
/****************************************************************************/

/*
 *   Miscellaneous defines
 */


/*
 *   Structure declarations
 */


/*
 * Prototype statements
 */

/* Checkmem.c */

RC APIENTRY CheckMem(PVOID, ULONG, ULONG);
