#**	makefile for CD Audio Media Component Interface Drivers
#
#
# ***************************************************************************
# *
# *			                   
# *
# *		    Copyright (c) IBM Corporation  1990, 1991
# *			      All Rights Reserved
# *
# ***************************************************************************

.SUFFIXES:	.asm .c .obj .lst .def .lnk .sys .sym .dll .lib

####################################
#	Definitions for C Compiler #
####################################

CC=icc
CFLAGS= /C /Gs- /Ki- /W3 /Ss+ /C+ /Ge- /Ms /Gd- /Gm+ /DINCL_32
DEBUG	   = /Ti+ /O-

##########################################
#	Definitions for new style linker #
##########################################

LINK= link386
LFLAGS= /map /noi
LIBS= OS2386.LIB DDE4MBS.LIB

#	Rules for generating object and linker response and definition files

.c.obj:
	$(CC) $(CFLAGS) $*.c

.dll.lib:
	implib $*.lib $*.dll

.sys.sym:
	mapsym $*


#	List of object files required

all: ibmcdrt.dll cdaudiot.dll

ibmcdrt.dll: ibmcdrom.obj cdmccomn.obj cdmcinit.obj hhpheap.obj \
             ibmcdrom.lnk ibmcdrom.def
	$(LINK) $(LFLAGS) @ibmcdrom.lnk

ibmcdrom.def: makefile
	@echo Creating file <<$(@B).def
LIBRARY IBMCDRT INITINSTANCE
DESCRIPTION 'IBM CD-ROM Toolkit MCI Driver, (c) IBM Corp 1991'
DATA MULTIPLE NONSHARED
HEAPSIZE	  44120
STACKSIZE	  53000
IMPORTS
  mdm.mdmDriverNotify
  mdm.mdmSyncNotify
EXPORTS
  vsdDriverEntry
<<keep

ibmcdrom.lnk: makefile
	@echo Creating file <<$(@B).lnk
ibmcdrom cdmccomn cdmcinit hhpheap
ibmcdrt.dll
ibmcdrom.map $(LFLAGS)
$(LIBS)
ibmcdrom.def;
<<keep

cdaudiot.dll:  cdaudio.obj cdaudpro.obj cdaudutl.obj cdmccomn.obj\
               cdmcinit.obj hhpheap.obj cdaudio.lnk cdaudio.def
	$(LINK) $(LFLAGS) @cdaudio.lnk

cdaudio.def: makefile
	@echo Creating file <<$(@B).def
LIBRARY CDAUDIOT INITINSTANCE
DESCRIPTION 'CD Audio Toolkit MCI Driver, (c) IBM Corp 1991'
DATA MULTIPLE NONSHARED
HEAPSIZE	  44120
STACKSIZE	  53000
IMPORTS
  mdm.mdmDriverNotify
  mdm.mciSendCommand
  mdm.mciConnection
  mdm.mciQueryConnections
  mdm.mciQueryDefaultConnections
EXPORTS
   mciDriverEntry
<<keep

cdaudio.lnk: makefile
	@echo Creating file <<$(@B).lnk
cdaudio cdaudpro cdaudutl cdmccomn cdmcinit hhpheap
cdaudiot.dll
cdaudio.map $(LFLAGS)
$(LIBS)
cdaudio.def;
<<keep

